kind: ConfigMap
apiVersion: v1
metadata:
  # Must match the 'spring.application.name' property of the application
  name: mysqlparam-config
data:
  mysqlparam.properties: |
    # MYSQL_SERVICE_NAME=mysql.yang.svc:3306
    serverName=mysql
    database=sampledb
    username=kalix
    password=kalix
    # Override the configuration properties here
    # pool.size.core: 1
    # pool.size.max: 16